In [1]:
import pandas as pd
import numpy as np
from neural import MLPptorch
import torch
import torch.nn as nn

In [5]:
# функция обучения
def train(x, y, num_iter):
    for i in range(0,num_iter):
        pred = net.forward(x)
        loss = lossFn(pred, y)
        loss.backward()
        optimizer.step()
        if i%(num_iter/10)==0:
           #print(optimizer.param_groups[-1]['lr'])
           print('Ошибка на ' + str(i) + ' итерации: ', loss.item())
    return loss.item()

In [6]:
df = pd.read_csv('data.csv')
df = df.iloc[np.random.permutation(len(df))]

X = df.iloc[0:100, 0:3].values
y = df.iloc[0:100, 4]
y = y.map({'Iris-setosa': 1, 'Iris-virginica': 2, 'Iris-versicolor':3}).values.reshape(-1,1)
Y = np.zeros((y.shape[0], np.unique(y).shape[0]))
for i in np.unique(y):
    Y[:,i-1] = np.where(y == i, 1, 0).reshape(1,-1)

X_test = df.iloc[100:150, 0:3].values
y = df.iloc[100:150, 4]
y = y.map({'Iris-setosa': 1, 'Iris-virginica': 2, 'Iris-versicolor':3}).values.reshape(-1,1)
Y_test = np.zeros((y.shape[0], np.unique(y).shape[0]))
for i in np.unique(y):
    Y_test[:,i-1] = np.where(y == i, 1, 0).reshape(1,-1)

In [7]:
inputSize = X.shape[1] # количество входных сигналов равно количеству признаков задачи 
hiddenSizes = 50 # задаем число нейронов скрытого слоя 
outputSize = Y.shape[1] if len(Y.shape) else 1 # количество выходных сигналов равно количеству классов задачи


net = MLPptorch(inputSize,hiddenSizes,outputSize)
print(net)
lossFn = nn.MSELoss()

optimizer = torch.optim.SGD(net.parameters(), lr = 0.05)

# как работает регуляризация
# optimizer = torch.optim.SGD(net.parameters(), lr=0.05, weight_decay=0.1)

loss_ = train(torch.from_numpy(X.astype(np.float32)), 
              torch.from_numpy(Y.astype(np.float32)), 5000)

# for name, param in net.named_parameters():
#     print(name, param)

pred = net.forward(torch.from_numpy(X.astype(np.float32))).detach().numpy()
err = sum(abs((pred>0.5)-Y))
print(err)   

pred = net.forward(torch.from_numpy(X_test.astype(np.float32))).detach().numpy()
err = sum(abs((pred>0.5)-Y_test))
print(err)

MLPptorch(
  (layers): Sequential(
    (0): Linear(in_features=3, out_features=50, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=50, out_features=3, bias=True)
    (3): Sigmoid()
  )
)
Ошибка на 0 итерации:  0.25991252064704895
Ошибка на 500 итерации:  0.022043487057089806
Ошибка на 1000 итерации:  0.02139892242848873
Ошибка на 1500 итерации:  0.01884395256638527
Ошибка на 2000 итерации:  0.013337817043066025
Ошибка на 2500 итерации:  0.013338174670934677
Ошибка на 3000 итерации:  0.013426289893686771
Ошибка на 3500 итерации:  0.013333229348063469
Ошибка на 4000 итерации:  0.013333248905837536
Ошибка на 4500 итерации:  0.01333322562277317
[0. 2. 2.]
[0. 2. 3.]


In [8]:
from neural_ import MLPptorch

In [9]:
net = MLPptorch(inputSize,hiddenSizes,outputSize)
print(net)
lossFn = nn.MSELoss()

optimizer = torch.optim.SGD(net.parameters(), lr = 0.0005)

# как работает регуляризация
# optimizer = torch.optim.SGD(net.parameters(), lr=0.05, weight_decay=0.1)

loss_ = train(torch.from_numpy(X.astype(np.float32)), 
              torch.from_numpy(Y.astype(np.float32)), 5000)

# for name, param in net.named_parameters():
#     print(name, param)

pred = net.forward(torch.from_numpy(X.astype(np.float32))).detach().numpy()
err = sum(abs((pred>0.5)-Y))
print(err)   

pred = net.forward(torch.from_numpy(X_test.astype(np.float32))).detach().numpy()
err = sum(abs((pred>0.5)-Y_test))
print(err)

MLPptorch(
  (layers): Sequential(
    (0): Linear(in_features=3, out_features=50, bias=True)
    (1): ReLU()
    (2): Linear(in_features=50, out_features=50, bias=True)
    (3): ReLU()
    (4): Linear(in_features=50, out_features=3, bias=True)
  )
)
Ошибка на 0 итерации:  0.5171573758125305
Ошибка на 500 итерации:  0.06660741567611694
Ошибка на 1000 итерации:  0.04604059085249901
Ошибка на 1500 итерации:  0.040344227105379105
Ошибка на 2000 итерации:  0.04269195720553398
Ошибка на 2500 итерации:  0.03715496510267258
Ошибка на 3000 итерации:  0.03170688822865486
Ошибка на 3500 итерации:  0.028227172791957855
Ошибка на 4000 итерации:  0.02864379622042179
Ошибка на 4500 итерации:  0.024732796475291252
[0. 3. 3.]
[0. 3. 3.]


In [10]:
# Вывод - класс многослойного перцептрона MLPptorch обучается с функцией активации Sigmoid со скоростью обучения = .05
# и с функцией активации Relu со скоростью обучения = .0005.
# имеет схожие результаты, но у relu веса не имеют ограничений в области положительных значений,
# поэтому необходимо выбирать более низкую скорость обучения.